### ISSUE TITLE
Supervisors in Rabble?

### ISSUE THREAD

**Issue by z1mvader** [andrewjstone/rabble#25]
Hey! I just posted your repo into reddit because I thought it was worth it mentioning it :). Someone wrote about implementing a supervisor on rabble. I am no expert but I'm willing to help on it. https://www.reddit.com/r/erlang/comments/6a75cr/actor_model_concurrency_in_rust/

**Comment by andrewjstone** [comment]
Hi @z1mvader, Thanks for the interested and offer!

I actually had an issue, #7, open for this, but closed it by mistake a few weeks ago. While ii think general purpose supervisors are probably impossible, at least the way they work in Erlang, We can implement some supervision to handle panics by using [catch_unwind](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html). I'm going to close this issue and reference you over there, so we can put all the relevant info in one issue.
